#!/bin/bash
#-------------------------------------------------------
# Bash-script autogenerated by im4java
# at Sat Sep 17 14:53:29 EDT 2022
#-------------------------------------------------------

The RESIZE line